### ISSUE TITLE
Scroll to specific div

### ISSUE THREAD

**Issue by alishadot** [vfeskov/vanilla-back-to-top#6]
Hi, thanks for creating this! 

I saw that the description states:

"Simple and tiny Back To Top button with no dependencies, for whole window or specific(s) div(s)."
I'm hoping to scroll back to a div tag named "#contents". 

Can you please let me know how to scroll back to a particular div (which happens to be further down the page), as opposed to a set number of pixels from the top.

Thank you

**Comment by vfeskov** [comment]
i added `scrollContainer` option, it might be enough:
```
addBackToTop({
  scrollContainer: document.getElementById('content')
});
```

if it's not enough, i made `onClickScrollTo` option accept a function instead of a number:
```
addBackToTop({
  onClickScrollTo: () => document.getElementById('content'). getBoundingClientRect().top
})
```
the function might require some changes based on your html structure but you can make it work, also check this: https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
